### ISSUE TITLE
Add a strong name to the package

### ISSUE THREAD

**Issue by ycrumeyrolle** [gfoidl/Base64#116]
In order to allow integration to applications or packages that are themself with a strong name, this package should be signed.
THis is generating the following warning message:
`CSC : warning CS8002: Referenced assembly 'gfoidl.Base64, Version=1.0.761.1, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming

**Comment by gfoidl** [comment]
Good idea (although I don't like strong names 😉). Will address this in the next days.
