### ISSUE TITLE
Mark the `gfoidl.Analyzers` dependency as a private asset

### ISSUE THREAD

**Issue by ycrumeyrolle** [gfoidl/Base64#153]
The `gfoidl.Analyzers` may generates a lots of undesired warnings when the package `gfoidl.Base64` is in other projects. 
On my project, this is generating 184 warnings :(
May be the attribute  `PrivateAssets` on the package will fix the issue ?

**Comment by ycrumeyrolle** [comment]
Wondering if the same could be applyied to `LocalsInit.Fody`  (is it a dev depedency?)

**Comment by gfoidl** [comment]
> On my project, this is generating 184 warnings :(

Oh, this was not my intention. Sorry.

> Wondering if the same could be applyied to `LocalsInit.Fody` (is it a dev depedency?)

Makes sense.

> `gfoidl.Analyzers`

The purpose is that the "internal" encoders aren't access directly, they should be accessed via `Base64.Default` or `Base64.Url`.
To allow the JIT to devirtualize them, they need to be public.

I'll have a look on how to fix this. Maybe this analyzer should just look at the specific namespace, so any other code won't be considered.

Thanks for reporting!

**Comment by ycrumeyrolle** [comment]
> Maybe this analyzer should just look at the specific namespace, so any other code won't be considered.

👍

**Comment by gfoidl** [comment]
> Wondering if the same could be applyied to `LocalsInit.Fody` (is it a dev depedency?)

Interesting, it's already set: https://github.com/gfoidl/Base64/blob/2e2ebc9b8f9c1ded97d7b8c03681ea9bb50dfd3b/source/gfoidl.Base64/gfoidl.Base64.csproj#L31-L34

Is there something missing? Do you have any clue therefore?

**Comment by gfoidl** [comment]
To my last comment: That's `Fody` and not `LocalsInit.Fody`. So please ignore this comment.

**Comment by gfoidl** [comment]
The part for the analyzer is tracked in https://github.com/gfoidl/Analyzers/issues/4
